Interactive Demo Project + New Methods / Replies
SaviorXTanren/StreamingClientLibrary pull request #3
Opened 2017-06-26 19:26 UTC by ttaber

- Created Interactive Demo Project
- Created OnParticipant??? Methods / Events
- Added Outstanding Callbacks for async reply processing
- Added GetScenes Method / Reply
- Fixed await timeouts on Get Scenes / Participants
- Wired up server response to see raw feedback

2017-06-27 02:08 UTC, SaviorXTanren requested changes
Overall looks pretty good, let me know if you have any questions about my feedback. Also don't forget to add unit tests for the new methods you made.

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/InteractiveClient.cs
> +        public event EventHandler<string> ReceiveOccurred;
I don't really understand the point of this method? The APIs for interactive state that there's only two types of methods that will be transmitted back to the client, replies and methods. Both of those are covered by ReplyOccurred and MethodOccurred.

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/InteractiveClient.cs
> +        public event EventHandler<InteractiveOnParticipantLeaveModel> OnParticipantLeaveOccurred;
There's a lot of excess spaces that can be removed. Ideally, all of the specific events can be bundled together to save on unnecessary lines in the file.

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/InteractiveClient.cs
> +        private Dictionary<uint, string> registeredCallbacks = new Dictionary<uint, string>();
I'm not sure I understand the use case for this callbacks container? You're storing the packet IDs and the specific type of event that's being called, then you're checking to see if that packet ever comes back? I understand the code logic, but I don't fully understand the reasoning behind it and what benefit it provides. We're not doing any callback checks to see if we never receive a specific packet back, so I don't really understand the point.

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/Model/Interactive/InteractiveOnParticipantJoinModel.cs
> +        public List<InteractiveParticipantModel> participants{ get; set; }
Minor spacing before "{ get; set; }"

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/Model/Interactive/InteractiveOnParticipantLeaveModel.cs
> +        public List<InteractiveParticipantModel> participants{ get; set; }
Minor spacing before "{ get; set; }"

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/Model/Interactive/InteractiveOnParticipantUpdateModel.cs
> +        public List<InteractiveParticipantModel> participants{ get; set; }
Minor spacing before "{ get; set; }"

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/Model/Interactive/InteractiveParticipantModel.cs
> +/*
Debug comments? I don't really want us having to worry about documenting the expected results of the API, as that's Mixer's job to maintain.

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/Web/WebSocketClientBase.cs
> +        protected async Task Send(WebSocketPacket packet, bool checkIfAuthenticated = true, uint packetID = 0)
Why are you having Send commands send in the packet ID? The individual commands shouldn't have the worry about the logic of what packet ID they are, they should simply just send the packet and let the underlying logic determine the correct packet ID. I assume this is related to the packet ID dictionary you're storing in the interactive client?

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/InteractiveClient.cs
> +        public event EventHandler<InteractiveOnParticipantLeaveModel> OnParticipantLeaveOccurred;
I like the naming use of "On___". I'm good with changing all of the events to that.

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/InteractiveClient.cs
> +                switch (registeredCallbacks[replyPacket.id])
I'd look towards the ChatClient for simplification of this, once you remove the registered callbacks logic.

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/InteractiveClient.cs
> +        public async Task GetAllParticipants(uint from = 0)
What does the from parameter do? It's not obvious what the indication is.

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/Model/Interactive/InteractiveControl.cs
> +    public class InteractiveControl
InteractiveControlModel

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/Model/Interactive/InteractiveError.cs
> +    public class InteractiveError
InteractiveErrorModel

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/Model/Interactive/InteractiveGroup.cs
> +   public class InteractiveGroup
InteractiveGroupModel

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/Model/Interactive/InteractiveOnParticipantJoinModel.cs
> +   public class InteractiveOnParticipantJoinModel
There's no need to make multiple classes for the same data that lies at its core. You can remove OnLeave and OnUpdated models and just make a "InteractiveParticipantsChangedModel"

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/Model/Interactive/InteractiveOnSceneDeleteModel.cs
> +   public class InteractiveOnSceneDeleteModel
Remove the "On", keep that reserved for events themselves specifically.

2017-06-27 02:08 UTC, SaviorXTanren commented on Mixer.Base/Model/Interactive/InteractiveScene.cs
> +    public class InteractiveScene
InteractiveSceneModel

2017-06-27 03:48 UTC, verbatimt reviewed
Reviewed changes processed

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/InteractiveClient.cs
> +        public event EventHandler<string> ReceiveOccurred;
This method, and the accompanying event/methods will be stripped out. I was using it to assist generating the JSON responses to quickly build the classes using json2csharp.com

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/InteractiveClient.cs
> +        public event EventHandler<InteractiveOnParticipantLeaveModel> OnParticipantLeaveOccurred;
I blame Code Maid. Will see if I can tweak the rules a bit to compress it down

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/InteractiveClient.cs
> +        public async Task GetAllParticipants(uint from = 0)
Will add comments. Pseudo-logic for use is on page 19/20 of the spec but, in short, result array caps at 100 participants max but will indicate when you've received all. The "from" parameter is the timestamp of when the participant connected. Recommended initial call is always from 0. This can be dropped though if you feel it's better to let that requirement bubble up to the client.

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/Model/Interactive/InteractiveControl.cs
> +    public class InteractiveControl
Noted

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/Model/Interactive/InteractiveError.cs
> +    public class InteractiveError
Noted

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/Model/Interactive/InteractiveGroup.cs
> +   public class InteractiveGroup
Noted

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/Model/Interactive/InteractiveOnParticipantJoinModel.cs
> +        public List<InteractiveParticipantModel> participants{ get; set; }
Noted

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/Model/Interactive/InteractiveOnParticipantLeaveModel.cs
> +        public List<InteractiveParticipantModel> participants{ get; set; }
Noted

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/Model/Interactive/InteractiveOnParticipantUpdateModel.cs
> +        public List<InteractiveParticipantModel> participants{ get; set; }
Noted

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/Model/Interactive/InteractiveOnSceneDeleteModel.cs
> +   public class InteractiveOnSceneDeleteModel
Understood. Naming was originally based on the specific reply method.

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/Model/Interactive/InteractiveParticipantModel.cs
> +/*
Miss on my part. Removed.

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/Model/Interactive/InteractiveScene.cs
> +    public class InteractiveScene
Noted

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/InteractiveClient.cs
> +        public event EventHandler<InteractiveOnParticipantLeaveModel> OnParticipantLeaveOccurred;
Noted

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/InteractiveClient.cs
> +        private Dictionary<uint, string> registeredCallbacks = new Dictionary<uint, string>();
Based on the analysis of the spec, there is no type/response information of any kind which is returned in a reply and multiple replies which carry the same/similar data structure, but have very different post-receipt processing (i.e. getActiveParticipants vs getAllParticipants). The only information which is returned in a reply is the packet ID which is identical to the ID which was sent with the requesting method. That being said, I was planning on going back and expanding upon the dictionary to use a class rather than a string to allow for retry/expiration logic to be applied in the event an expected reply was never received.

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/InteractiveClient.cs
> +                switch (registeredCallbacks[replyPacket.id])
See comment regarding callback dictionary purpose

2017-06-27 03:48 UTC, verbatimt commented on Mixer.Base/Web/WebSocketClientBase.cs
> +        protected async Task Send(WebSocketPacket packet, bool checkIfAuthenticated = true, uint packetID = 0)
Correct. See comment regarding callback dictionary purpose.

2017-06-27 03:48 UTC, ttaber commented on Mixer.Base/Model/Interactive/InteractiveOnParticipantJoinModel.cs
> +   public class InteractiveOnParticipantJoinModel
Noted

2017-06-29 22:20 UTC, SaviorXTanren commented
Hey, I pushed some changes to the interactive branch for a suggestion on how to handle listening for the replies on interactive methods. Let me know your thoughts.

2017-07-03 06:53 UTC, closed without merging